### ISSUE TITLE
Display Health For Buildables.

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#103]
can you plz add a graphical display of health for all you buildings

**Comment by q3shafe** [comment]
This could be setup to work a lot like crosshair health on team games.   Otherwise it'll have to wait until the new UI is in place.

**Comment by q3shafe** [comment]
I don't really like how this would have to work with the net data.   It may make more sense just to add an indicator saying how many turrets, generators and whatnot your team has built.  this info is already passed over.

**Comment by q3shafe** [comment]
Since the number of buildables is based on server configuration, there is no way within the current netcode to accomplish this,  the gain is minimal compared to the amount of rewrite of the main engine net code, and the bandwidth overhead that would come with this.  We are already pushing the limits.
