### ISSUE TITLE
Characteristic 34 is not initialized with angrynerdbot errors 

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#111]
Characteristic 34 is not initialized with angrynerdbot errors

try this on trep_war_ring, trepidation game type.  May happen on other game types as well.

**Comment by q3shafe** [comment]
What is the verdict/solution on this?  can you post it here?

**Comment by angrynerd** [comment]
I cant find the solution skill 4 didnt have the problem and there is no
differences in skill 3 to 4 on skill 34

**Comment by q3shafe** [comment]
Reverted to an earlier version of the file and the errors seem to be gone.

**Comment by angrynerd** [comment]
What verson by chance did you revert to

On Apr 27, 2017 1:11 AM, "Shafe Shaffer" <notifications@github.com> wrote:

Closed #111 <https://github.com/q3shafe/trepidation/issues/111>.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/q3shafe/trepidation/issues/111#event-1059784181>, or mute
the thread

**Comment by q3shafe** [comment]
reverted to commit d5ab299abbd1b114276bf585c480a0aae74223b1.
