### ISSUE TITLE
Players dont die when falling off level OA_RPG3DM2_S

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#192]
When players fall off the map on the platforms below, they don't die.  This causes all the bots to get stuck down there.

See Screenshot.
![shot0012](https://user-images.githubusercontent.com/933257/53704319-c4351c00-3de9-11e9-9de3-6448158da527.jpg)
![shot0013](https://user-images.githubusercontent.com/933257/53704320-c4351c00-3de9-11e9-8636-4606338ef232.jpg)

**Comment by squiciene** [comment]
i know i addressed this issue.  heres a copy of the .bsp & the .ass
[maps.zip](https://github.com/q3shafe/trepidation/files/2949439/maps.zip)
this still works on my PC, but i havent yet installed the latest rebuild.

**Comment by angrynerd** [comment]
Ok this works and will be commited shortly. i must ask though as it seems aversion 2 has a bottom texture is that not appliable to this map?
![shot0033](https://user-images.githubusercontent.com/24483958/54090108-107edf80-4347-11e9-8357-8508a07af2e1.jpg)

**Comment by squiciene** [comment]
LOL.  that map does not have a bottom sky texture.  you might be confused, because there is a sub-floor under it to prevent most people from seeing the HOM effect caused by no bottom texture.   if you goto spectator mode & fly towards the wall you will see the HOM effect.  ( HOM = hall of mirrors)

the only sky texture that has a functional bottom is the one made by Gigon for the TREPXSUS map. but you cant see it from in game. i saw it in developer mode while re-designing the map.

if you like, i can send a copy of that map with only the hull so you can see it for yourself.

**Comment by angrynerd** [comment]
Well reguardless of it being an actuall bottom texture would that idea work
on this map?

**Comment by angrynerd** [comment]
I know from an old 2007 build that for a bit im pretty sure trepxus the
original had an issue with the hom effect on its sky box rather than the
floor.

**Comment by squiciene** [comment]
i can put a sub floor like aversion has, but since the floor is soo close, the effect would still be easily visible from the lower area of the map.    i could just seal the underside of the map off. put walls around all those passages.  then you wouldnt see any of it, but it would be a bit cramped for space.

**Comment by angrynerd** [comment]
Its like i dont want the walls their because it totally would be cramped
but the hom effect is just a pain. Idk what the best way to tackle it is.
