### ISSUE TITLE
station textures

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#202]
The pickup textures have been broken in the latest snapshot. I am not possotive on what caused it but i tested this with a snapshot that was before junction 2 was added and it works just fine. 
![shot0028](https://user-images.githubusercontent.com/24483958/54074370-b7884c00-425f-11e9-90c0-413246fef6fd.jpg)
i also tested it with a snapshot with and without the last 2 texture fixes to junction and it was still this way. also this is only one screenshot but it is this way for all similar textures, being weapon, health, item, and ammo pickup boxes or x's.

**Comment by squiciene** [comment]
once i get the game update i can fix this.   Shafe was talking about getting rid of the old versions of the maps i have remade, & just putting up a plaque or something to let people know Gigon had a hand in the map.      ....so do you guys want to keep this one?  put it in a map pack later maybe?

**Comment by angrynerd** [comment]
This was one that was to be kept. I have also noticed this does affect station145 because of it using the same texture.

**Comment by squiciene** [comment]
actually those are totally different textures. but they are all in the same folder.  i cant recall which shader file i wrote the script for mine in.  they do both look the same.    this sounds like a shader issue again.

i once tried to recreate his (because i broke it...lol) but i couldnt use his script. so i made copies of the textures, & wrote my own script for them.     i had to re-organise all the scripts i use not long ago, (because i broke a lot of the shader files that were in trep) & working on this particular script was one of the ones i was working with at the time.

shader files are very sensitive little creatures. LMAO       you may have to try different ways of organizing them to get them right.           or i will have to start from scratch, & re-re-organize all shader files.
with all the new changes, this may become inevitable for me.

**Comment by angrynerd** [comment]
Thats the thing though cleay it was in the right place and was only messed
up after the snapshot with junction 2... I have no idea.

**Comment by q3shafe** [comment]
Have a look now..

**Comment by angrynerd** [comment]
fixed
