### ISSUE TITLE
Levelshots

### ISSUE THREAD

**Issue by angrynerd** [q3shafe/trepidation#221]
Ok so dystopia2 and battlefield 2 dont have level shots. This is an easy fix.

**Comment by q3shafe** [comment]
These shouldn't exist... they should just be dystopia and ctf_battlefield now..

**Comment by angrynerd** [comment]
Then there is something wrong...

**Comment by angrynerd** [comment]
Ok so i checked this in the files and your roght it doesnt exit butbif i go
to the single player menu it says its there but wont let me click fight.

**Comment by q3shafe** [comment]
an extra arena file floating around in there... fixed.

**Comment by squiciene** [comment]
this issue concerns maps junction 2, war ring 2 & trepxsus 2.  levelshots are not present due to renaming maps.  the levelshots simply need to be re-named.  however, this creates a new issue.  it was said that the old versions of those maps would later be released as a map pack. if we alter the names i gave the re-makes, then we must also re-name all the old ones before releasing the map pack or conflicts will occur.
i understand what was being attempted by renaming, but i think the original names would cause less headache.
concerning Shafes last comment - now that we have a single arena file for all maps, station 144 arena file needs to be removed from pak1-ccdata & station 145 arena file needs to be removed from pak0-gpl2data
