### ISSUE TITLE
Could not load default model barret

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#222]
Could not load default model barret error, then throws you off the server.

This happens when a person is on the server with a player skin that isn't loaded on the server and the map changes.

**Comment by q3shafe** [comment]
I'm pretty sure this is just a result of something goofy by using a non-trep player model on the server.  I cannot reproduce this in unit tests.

The next live player testing we do, we will not have any non stock player models on the server.

**Comment by angrynerd** [comment]
Alright i will make note of this. On a side note though how were you
testing it because what caused was the thing you put in place to load the
default model when the models arent on the server. I had mistalenly
included the doom and toom raider models in the clients amd so people who
joined with those shouod have had the default berett model. This instead
produced and error and it wouldnt load. The models that you did have, the
bobafett one, worked fine. I wont include those with the clients anymore
but this is an issue at any rate.
